name: music_app
channels:
  - defaults
dependencies:
  - python=3.10.4
  - sqlite=3.45.3
  - pip=21.2.4
  - pip:
    - arrow==1.3.0
    - asgiref==3.8.1
    - attrs==25.3.0
    - babel==2.17.0
    - bcrypt==4.3.0
    - blessed==1.20.0
    - certifi==2025.1.31
    - cffi==1.17.1
    - chardet==5.2.0
    - charset-normalizer==3.4.1
    - contourpy==1.3.2
    - croniter==6.0.0
    - cryptography==44.0.2
    - cycler==0.12.1
    - dask==2025.3.0
    - defusedxml==0.7.1
    - distro==1.9.0
    - Django==4.2.20
    - django-ajax-selects==3.0.3
    - django-cors-headers==4.7.0
    - django-crispy-forms==1.14.0
    - django-csp==3.8
    - django-countries==7.6.1
    - django-db-logger==0.1.13
    - django-import-export==4.3.7
    - django-filter==25.1
    - django-nested-admin==4.1.1
    - django-phonenumber-field==8.1.0
    - django-phonenumbers==1.0.1
    - django-picklefield==3.3
    - django-q==1.3.9
    - django-jazzmin==3.0.1
    - django-easy-audit==1.3.6
    - django-admin-charts==1.5.0
    - docker==7.1.0
    - docker-compose==1.29.2
    - dockerpty==0.4.1
    - docopt==0.6.2
    - docx==0.2.4
    - et-xmlfile==2.0.0
    - fonttools==4.57.0
    - idna==3.10
    - image==1.5.33
    - isodate==0.7.2
    - jsonschema==3.2.0
    - kaleido==0.2.1
    - kiwisolver==1.4.8
    - lxml==5.3.2
    - matplotlib==3.10.1
    - msrest==0.7.1
    - numpy==2.2.4
    - oauthlib==3.2.2
    - openpyxl==3.1.5
    - packaging==24.2
    - pandas==2.2.3
    - paramiko==3.5.1
    - pathlib==1.0.1
    - phonenumbers==9.0.3
    - pillow==11.2.1
    - plotly==6.0.1
    - polars==1.27.1
    - psutil==7.0.0
    # - pyarrow==19.0.1
    - pycparser==2.22
    - PyNaCl==1.5.0
    - pyparsing==3.2.3
    - pyrsistent==0.20.0
    - python-dateutil==2.9.0
    - python-docx==1.1.2
    - python-dotenv==0.21.1
    - python-json-logger==3.3.0
    - python-monkey-business==1.1.0
    - pytz==2025.2
    - PyYAML==5.3.1
    - redis==3.5.3
    - reportlab==4.3.1
    - requests==2.32.3
    - requests-oauthlib==2.0.0
    - six==1.17.0
    - sqlparse==0.5.3
    - tableauhyperapi==0.0.21408
    - tenacity==9.1.2
    - texttable==1.7.0
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.4.0
    - wcwidth==0.2.13
    - websocket-client==0.59.0
    - whitenoise==6.3.0
    - wincertstore==0.2
    - xlrd==2.0.1
    - xlsxdocument==1.3.10
    - XlsxWriter==3.2.2
    - xlwt==1.3.0
    - pytest==8.3.5
    - pytest-cov==6.1.1
    - pytest-django==4.11.1
    - google-api-python-client
    - beautifulsoup4==4.14.2
    #uncomment when creating the environment the first time locally
    - psycopg2==2.9.10